In [10]:
from torch.utils.data import RandomSampler
import torch
import numpy as np
import random

In [35]:
seed = 33
generator = torch.Generator()
generator = generator.manual_seed(seed)
aa = torch.randint(1, 3, (3,), generator=generator)
# torch.randint(1, 3, (3,), generator=generator)


In [43]:
[i for i in iter(RandomSampler(aa, generator=generator))]

[2, 0, 1]

In [7]:
seed = 33
generator = torch.Generator()
generator.manual_seed(0)
torch.cuda.manual_seed(0)
np.random.seed(0)
random.seed(0)
torch.backends.cudnn.deterministic=True

In [31]:
aa = torch.randint(1, 60, (32,), generator=generator)
aa
# sampler = RandomSampler(aa, generator=generator)

tensor([19, 33,  4, 55, 48, 50, 36, 45, 13, 30, 59, 26,  6, 12, 44, 48,  6,  4,
        50, 20,  4, 28, 35, 30, 38, 19,  4, 11, 45, 47, 13, 54])

In [34]:
generator.initial_seed()

0

In [3]:
seed = 33
generator = torch.Generator()
generator.manual_seed(0)
# generator.initial_seed()
torch.randint(1, 100, (3,), generator=generator)
# 

tensor([99, 19, 57])

In [38]:
generator.manual_seed(3)

In [42]:
int(torch.empty((), dtype=torch.int64).random_().item())

7264428964792235449

In [40]:
generator.seed()

8168956538510561777

In [20]:
torch.manual_seed(0)
torch.cuda.manual_seed(0)
l = torch.nn.Linear(3, 4)
l.weight

Parameter containing:
tensor([[-0.0043,  0.3097, -0.4752],
        [-0.4249, -0.2224,  0.1548],
        [-0.0114,  0.4578, -0.0512],
        [ 0.1528, -0.1745, -0.1135]], device='cuda:2', requires_grad=True)

Parameter containing:
tensor([[-0.0043,  0.3097, -0.4752],
        [-0.4249, -0.2224,  0.1548],
        [-0.0114,  0.4578, -0.0512],
        [ 0.1528, -0.1745, -0.1135]], requires_grad=True)

NameError: name 'aa' is not defined

In [27]:
aa = torch.randint(1, 60, (32,), generator=generator)
aa

tensor([ 9, 22, 26, 17, 25, 41, 35, 28, 32, 12, 30, 12, 47, 54, 18, 34, 53,  5,
         7, 46, 31, 54, 25, 48, 45, 39, 56, 43, 11, 14, 19, 46])

tensor([17, 59, 17, 14, 48, 16, 41,  6, 19, 59, 45, 16, 57, 25, 51, 25, 10, 46,
        59, 16, 59, 48, 45, 14, 46, 54, 50, 11,  9, 43, 32, 36])

In [ ]:
next(iter(sampler))

In [25]:
aa

tensor([[19, 37, 35, 40],
        [10, 30, 31, 46],
        [20,  9, 39, 37],
        [29, 31,  6, 41],
        [ 9, 45, 15,  9],
        [42, 10, 10, 22],
        [ 7,  7, 49, 48],
        [43, 26, 15, 43],
        [29, 22, 41, 40],
        [18, 15, 41, 28],
        [ 0,  7,  6,  7],
        [26, 36, 21, 31],
        [38, 29, 32, 27],
        [32, 13, 18,  2],
        [34, 20, 26, 16],
        [17, 39, 43, 41],
        [33,  7, 17, 18],
        [46,  0, 22, 41],
        [31, 28,  5, 45],
        [25, 42, 38, 20],
        [41, 13, 38, 26],
        [ 7,  6, 48, 46],
        [42, 14,  4, 15],
        [19, 41, 22, 33],
        [ 0, 19, 39, 25],
        [16, 16, 24, 47],
        [23, 21, 35,  8],
        [13, 38, 10, 42],
        [36, 44, 18, 27],
        [32, 49, 28, 38],
        [30,  6, 36,  6],
        [46,  5, 38, 22],
        [21, 41, 29, 10],
        [45,  2,  3, 23],
        [19, 35,  9,  4],
        [47, 40, 30,  1],
        [21, 32, 49, 39],
        [17, 12, 13, 27],
        [45,

In [14]:
aa = torch.randint(50, (100,4))

In [16]:
seed = int(torch.empty((), dtype=torch.int64).random_().item())
generator = torch.Generator()
generator.manual_seed(seed)


In [8]:
p_matrix

TypeError: 'PCMCI' object is not subscriptable

AttributeError: 'DataFrame' object has no attribute 'var_names'

({0: 26304},
 321,
 <bound method PCMCI.convert_to_string_graph of <tigramite.pcmci.PCMCI object at 0x7fd4aada91c0>>)

In [35]:
seed = 33
generator = torch.Generator()
generator.manual_seed(seed)

In [39]:
torch.randint(1, 100, (3,), generator=generator)


tensor([12, 17, 96])

In [1]:
import torch
from torch_timeseries.nn.dil_encoder import DILEncoder


encoder = DILEncoder(8, 130,in_dim=1, middle_channel=64,dilation_exponential=2, layers=5)
data = torch.randn(64, 1, 8, 130)

encoder(data).shape

/root/anaconda3/envs/pytorch_timeseries/lib/python3.7/site-packages/tqdm-4.64.0-py3.7.egg/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


torch.Size([64, 64, 8, 1])

In [8]:

import torch
from torch_timeseries.nn.net import Net
encoder = Net(8, 130,in_dim=1, embed_dim=8, middle_channel=8, seq_out=1,dilation_exponential=2, layers=5)
data = torch.randn(64, 1, 8, 130)
encoder(data).shape


torch.Size([64, 1, 8, 1])

In [2]:
torch.__version__

'1.11.0'


                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.15.2) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['pyg']

pkgs/main/linux-64       [<=>                 ] (00m:00s) 
pkgs/main/linux-64       [=>   

In [1]:
from torch_timeseries.nn.mtcsg import MTCSG, _h_A
import torch
node_num = 8
model = MTCSG(node_num , 130, middle_channel=16, seq_out=1,causal_aggr_layers=1)
data = torch.randn(64, 1, 8, 130)
model(data)


h_A = _h_A(model.weighted_A, node_num )



/root/anaconda3/envs/pytorch_timeseries/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2022-12-07 19:34:02.965 | INFO     | torch_timeseries.nn.mtcsg:forward:40 - x shape : torch.Size([64, 16, 8, 1])
2022-12-07 19:34:02.966 | INFO     | torch_timeseries.nn.mtcsg:forward:43 - x shape : torch.Size([64, 8, 16])


TypeError: conv2d() received an invalid combination of arguments - got (ReLU, Parameter, Parameter, tuple, tuple, tuple, int), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (!ReLU!, !Parameter!, !Parameter!, !tuple!, !tuple!, !tuple!, int)
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (!ReLU!, !Parameter!, !Parameter!, !tuple!, !tuple!, !tuple!, int)
